version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.1

jobs:
  git-to-s3:
    docker:
      - image: cimg/base:stable
    environment:
      CIRCLE_BRANCH: << pipeline.git.branch >>
    steps:
      - checkout
      - run:
          name: The Second Step
          command: |
            ls -al
            echo "Building branch $CIRCLE_BRANCH"
      - aws-s3/copy:
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: index.html
          to: s3://pradeep-cicd-static-website/$CIRCLE_BRANCH/             
workflows:
  s3-website-workflow:
    jobs:
      - git-to-s3