version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.1

jobs:
  git-to-s3:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - when:
          condition:
            equal: [ dev, << pipeline.git.branch >> ]
          steps:
            - run:
                name: The Second Step
                command: |
                  ls -al
                  echo '^^^The files in your repo^^^'
                  echo "Building branch << pipeline.git.branch >>"
            - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
            - aws-s3/sync: 
                from: dev
                to: s3://pradeep-cicd-static-website/dev/
            - aws-s3/copy:
                aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
                aws-region: AWS_REGION_BLUE
                aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
                from: index.html
                to: s3://pradeep-cicd-static-website/dev/
      - when:
          condition:
            equal: [ QA, << pipeline.git.branch >> ]
          steps:
            - run:
                name: The Second Step
                command: |
                  ls -al
                  echo '^^^The files in your repo^^^'
                  echo "Building branch << pipeline.git.branch >>"
            - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
            - aws-s3/sync: 
                from: QA
                to: s3://pradeep-cicd-static-website/QA/
            - aws-s3/copy:
                aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
                aws-region: AWS_REGION_BLUE
                aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
                from: index.html
                to: s3://pradeep-cicd-static-website/QA/
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run:
                name: The Second Step
                command: |
                  ls -al
                  echo '^^^The files in your repo^^^'
                  echo "Building branch << pipeline.git.branch >>"
            - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
            - aws-s3/sync: 
                from: master
                to: s3://pradeep-cicd-static-website/master/
            - aws-s3/copy:
                aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
                aws-region: AWS_REGION_BLUE
                aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
                from: index.html
                to: s3://pradeep-cicd-static-website/master/                    
workflows:
  s3-website-workflow:
    jobs:
      - git-to-s3